### ISSUE TITLE
String not highlighted if containing hyphen or slash

### ISSUE THREAD

**Issue by ignamartinoli** [foxyseta/tree-sitter-prolog#1]
Testing on Neovim with

```prolog
test(a, "a-b").
```

`"a-b"` is not getting highlighted as a string.

It's caused by the hyphen (`-`) character.

The slash (`/`) character triggers this too.

![20240724 - 17:16:17](https://github.com/user-attachments/assets/7588b15b-dfea-4bcb-9f79-5913d383665c)

**Comment by foxyseta** [comment]
Thank you for providing me with a minimal example! (This repository is actually just a mirror of https://codeberg.org/foxy/tree-sitter-prolog. I will disable this issue tracker later so that people do not get confused again.)

I should have fixed this issue with 93c69d2. I added a testcase inspired by this issue (https://codeberg.org/foxy/tree-sitter-prolog/src/commit/93c69d2f84d8a167c0a3f4a8d51ccefe365a4dc8/grammars/prolog/test/corpus/simple.txt#L66) and it is passing now.

It looks like you are using nvim-treesitter (nice!). It might take a while for that project to update its dependency on this grammar.

**Comment by ignamartinoli** [comment]
Hey. It works perfectly now. Thanks!
